### ISSUE TITLE
[Note] 브라우저 종료시 op update

### ISSUE THREAD

**Issue by chahtk** [njsh4261/SGS_Last_Punch#152]
Note-Main-index 214줄 todo 주석

**Comment by chahtk** [comment]
브라우저 종료시 op와 content(all)을 동시에 저장하는 것에 리스크가 존재할 수 있음
- op를 먼저 저장하고, 웹소켓에 이를 알림. 직후 content(updateAll)을 저장함
- op 업데이트를 소켓으로부터 전달받은 유저는 노트 서버에 get OP를 하지만 update all API 때문에 op가 비워져있음

**Comment by chahtk** [comment]
차라리  유저가 타이핑 도중 나가버리는 특수 상황에서는 다른 유저들이 update All에 대해 알림을 받고 갱신하는게 어떨까?
- 안정성 높아질 것 같음
- 잦은 일이 아니기 때문에 비용적으로 큰 증가는 없어보임

**Comment by SooKim1110** [comment]
전체 문서를 저장할 때 op 배열을 빈 배열로 만들지 말고 일정량의 op는 남겨둠.
get specific note할 때는 content 가 업데이트된 timestamp 이후의 op들만 배열에 넣어서 response

**Comment by chahtk** [comment]
테스트 필요
