### ISSUE TITLE
API 요청 - 유저 정보 (id, name)

### ISSUE THREAD

**Issue by chahtk** [njsh4261/SGS_Last_Punch#169]
로그인 했을 때 **유저 정보**가 필요합니다. (note 서버에서 유저 id와 name이 필요합니다)
그래서 지수님께서 **로그인 성공시** 응답으로 유저 정보를 주도록 API를 수정해주셨으나, 다시 생각해보니 유저 정보를 받는 정확한 시점은 **'welcome' 페이지에 진입**할 때입니다. 현재 **토큰** 존재 여부에 따라 바로 welcome 페이지로 가기 때문입니다.

따라서 워크스페이스 리스트를 받아올 때, 혹은 별도의 본인 유저 정보를 가져오는 API가 필요합니다. 이에 대한 @njsh4261 님의 생각이 궁금합니다.

구현하신다면 유저 정보를 가져오는 코드는 지수님께서 작성하셨다고 하니 참고하시면 좋을 것 같습니다.

**Comment by njsh4261** [comment]
User Id를 주었을 때 user 하나의 정보를 가져오는 API를 하나 추가하겠습니다. 필요한 시점에서 호출해 주세요.
