### ISSUE TITLE
[Workspace-Account] get accounts by email (like) API

### ISSUE THREAD

**Issue by chahtk** [njsh4261/SGS_Last_Punch#180]
### 발생 상황
postman의 WorkspaceServer- Account - 'get accounts by email' 을 SEND해보면 404 에러 발생

### 예상원인
- 게이트웨이에서의 라우팅

**Comment by njsh4261** [comment]
#186 PR 통해서 게이트웨이 라우팅 수정했습니다. 현재 `POST /account` 및 `GET /account/self` API가 잘 동작하는 상태이고, API 문서는 추후 수정 예정입니다.
