### ISSUE TITLE
[Workspace 초대] 

### ISSUE THREAD

**Issue by chahtk** [njsh4261/SGS_Last_Punch#194]
### 상황

`POST /workspace/member`로  바디에 wsId(number), accountId(number)를 넣어 보냈는데 500에러가 발생

### 스크린샷

- 브라우저

![image](https://user-images.githubusercontent.com/44664867/152772761-5330b6f5-0051-41a8-92dd-f418992be2a2.png)

- 포스트맨(헤더)

![image](https://user-images.githubusercontent.com/44664867/152773036-524002eb-711b-4971-a9c5-60b7f35764b3.png)

- 포스트맨(바디)

![image](https://user-images.githubusercontent.com/44664867/152773081-1c74e184-235e-4b29-ac87-4b9abc501578.png)

- 포스트맨(응답)

![image](https://user-images.githubusercontent.com/44664867/152773132-ce521212-ab5c-4e0f-be37-0b14527d8cab.png)

**Comment by njsh4261** [comment]
필수 항목인 `workspaceId`가 누락되서 생긴 문제라 판단됩니다. `wsId`라고 임의로 줄이시면 안 됩니다. [API 문서](https://github.com/njsh4261/SGS_Last_Punch/blob/dev/docs/API_references/backend_workspace_apis.md) 혹은 [Postman 예시](https://github.com/njsh4261/SGS_Last_Punch/blob/dev/docs/API_references/WorkspaceServer.postman_collection.json)를 먼저 참조해 주세요.
