### ISSUE TITLE
[요청사항] email 검색시 본인 정보 제외해서 응답

### ISSUE THREAD

**Issue by chahtk** [njsh4261/SGS_Last_Punch#212]
현재 검색시 본인 정보를 포함하여 응답합니다. 그래서 본인이 본인을 초대하거나 dm을 보낼 수 있게 됩니다. 프론트 쪽에서도 처리는 가능하지만 코드가 꽤 추가 될 것 같아 요청드립니다
여유가 되실 때 이 부분 처리해주시면 감사하겠습니다~

**Comment by njsh4261** [comment]
resolved by #264
