### ISSUE TITLE
[요청사항] create note API 수정

### ISSUE THREAD

**Issue by chahtk** [njsh4261/SGS_Last_Punch#217]
- 현재 응답으로 noteId만 오기 때문에 노트 생성 후 타이틀을 표시할 수 없습니다.
- create note에 대한 응답을 `get note list` 의 응답과 동일한 형식으로 맞춰주실 수 있을까요?

**Comment by SooKim1110** [comment]
넵 수정하고 다시 코멘트 남겨 놓겠습니다!

**Comment by SooKim1110** [comment]
코드 수정하고 ec2 서버에도 반영하였습니다. 데이터 형식은 postman 예시를 참고해주세요.
