### ISSUE TITLE
[ws/channel 나가기] 400 error

### ISSUE THREAD

**Issue by chahtk** [njsh4261/SGS_Last_Punch#228]
- ws, channel 나가기 API를 보내면 400에러가 발생
- 채널 나가기 엔드포인트: `/channel/member?accountId=${accountId}&channelId=${channelId}`
- 저번에 상의한대로 body에는 데이터 추가하지 않았습니다

- 참고한 API 문서
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/44664867/153429407-dce31536-0cff-491b-a686-e03a6a72ebc3.png">

**Comment by njsh4261** [comment]
resolved by #264
