### ISSUE TITLE
[web - dm] dm 생성 및 전송 에러

### ISSUE THREAD

**Issue by SooKim1110** [njsh4261/SGS_Last_Punch#266]
멤버 조회, dm 생성까지는 잘 되는데 
1) dm 생성 후 채팅을 보냈을 때 채팅이 바로 보이지 않고 새로고침을 해야 보임
2) 새로고침을 할 때 만들어진 dm 방이 사라지는 경우가 있음
-> 이 경우 dm 방을 다시 만들면 이전에 보냈던 메세지의 일부가 저장되어 있음

**Comment by chahtk** [comment]
본인이 다른 사람한테 첫 DM을 보내면 lastMessage가 생겨서 리스트 렌더링 조건을 충족시킨다
-> 이 부분 로직 체크

**Comment by njsh4261** [comment]
워크스페이스 API 중 하나의 워크스페이스의 멤버 목록을 불러오는 API에서 오류로 인해 잘못된 lastMessage 정보를 요청하고 있었고, 이것이 현재 DM 목록이 호출되지 않는 이유일 수 있습니다. 수정 PR 올리겠습니다.
