### ISSUE TITLE
현재 비정상 채널 있음(Heroes/Marvle heroes)

### ISSUE THREAD

**Issue by chahtk** [njsh4261/SGS_Last_Punch#284]
<img width="514" alt="image" src="https://user-images.githubusercontent.com/44664867/154063018-7b8c50ab-d4be-4ff2-86ed-5b86e77ff703.png">

에러 처리 롤백 or 비정상 채널 삭제 부탁드립니다

**Comment by njsh4261** [comment]
백엔드 코드나 MySQL 스크립트 상의 문제는 아니고, 현재 테스트 스크립트에서 userId 2번 사용자가 2번 channel (Marvel heroes)의 소유자로 지정되어 있는데 테스트 중에 2번 사용자가 2번 채널을 탈퇴해서 생긴 문제로 보입니다.

임시 조치로 계정을 하나 만들고 현존하는 모든 채널의 소유권을 해당 유저에게 양도해 두었으며, 정상 동작하는 것을 확인했습니다.

수요일 중에 워크스페이스/채널 소유자가 해당 워크스페이스/채널을 나가려고 시도하는 경우 이를 방지하는 코드를 워크스페이스에 추가할 예정입니다. 해당 패치 이전에는 가급적 새로 생성한 워크스페이스/채널에서 소유자가 이탈한 후 해당 워크스페이스/채널 정보를 조회하는 경우를 지양해 주세요.

**Comment by chahtk** [comment]
감사합니다 지효님~~!!

2022년 2월 15일 (화) 오후 11:58, Jihyo Kim ***@***.***>님이 작성:
