### ISSUE TITLE
백엔드 서버 개선 요청사항 처리

### ISSUE THREAD

**Issue by njsh4261** [njsh4261/SGS_Last_Punch#309]
- [x] account/workspace 이미지 표시를 위한 워크스페이스 서버 소스코드 & DB 변경
- [x] <del> 워크스페이스/채널 수정 API 테스트 </del>
- [x] 워크스페이스/채널 멤버 목록 API가 출력하는 element에 email 추가
- [x] 프리젠스 서버 동시접속 처리: 다른 세션에서 접속 중인 사용자가 새로운 세션에서 접속했을 때 상태 표시를 `ONLINE`으로 변경하는 문제 수정

**Comment by GeonHyeongKim** [comment]
알림 해줘(요)~

**Comment by chahtk** [comment]
prescne에서 connect나 disconnect에 대한 메시지가 오고 있습니다!

**Comment by chahtk** [comment]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/44664867/154742124-f98b737f-a7b6-41d3-9052-aa46aae5055a.png">
subscribe한 토픽으로부터 온 msg입니다

**Comment by chahtk** [comment]
채널 나가기의 경우, 모든 사용자가 소유자라는 나가기 실패에 대한 에러 메시지가 옵니다.

**Comment by GeonHyeongKim** [comment]
> 채널 나가기의 경우, 모든 사용자가 소유자라는 나가기 실패에 대한 에러 메시지가 옵니다.

위 내용보고 테스트 해본결과 **맞습니다**
roleId를 body에 넣지 않더라도, normal 등급으로 처리해주시면 감사하겠습니다.
그리고 roleId 값의 의미가 (normal = 1, admin = 2, onwer = 3)가 맞는지 답글로 알려주세요~

**Comment by njsh4261** [comment]
프리젠스 관련 문제는 #335 PR 통해서 `CONNECT`는 그대로 전달, `DISCONNECT`는 `OFFLINE`으로 변경하여 보내도록 수정했습니다.
채널 멤버가 채널 나가기 / 다른 멤버를 채널에서 강퇴를 처리하는 API는 #328 PR에 수정내역 포함되어 있어 merge 후 반영될 예정입니다.
현재까지 올라온 모든 체크리스트가 해결되어 이슈를 닫습니다. 추가적인 문제가 발생하면 별도 이슈로 남겨주세요.
