### ISSUE TITLE
[요청사항 / Web] 채널 페이지에서 description 혹은 topic 표시

### ISSUE THREAD

**Issue by njsh4261** [njsh4261/SGS_Last_Punch#326]
![image](https://user-images.githubusercontent.com/54832818/154624506-227973f2-0f87-47c8-bc77-0e8230e80efe.png)

채널 이름 옆에 description 혹은 topic이 표시되면 좋을 것 같습니다!

**Comment by chahtk** [comment]
ws, channel description의 디폴트값이 다른 것 같습니다. 하나는 '', 하나는 Null인 것 같은데 일관성이 떨어지더라도 수정없이 현상태 유지 부탁드립니다.

**Comment by chahtk** [comment]
요청사항 완료했습니다! 코멘트 확인하시면 클로즈해주세요~
