### ISSUE TITLE
Note 기능 명세

### ISSUE THREAD

**Issue by chahtk** [njsh4261/SGS_Last_Punch#45]
모바일과 웹에서 notion의 어떤 기능들을 구현할지 논의

**Comment by chahtk** [comment]
## page

![image](https://user-images.githubusercontent.com/44664867/148736544-0879f1e7-46d9-46a0-9930-68a1c7699349.png)

- 좌측 사이드 바에서 `Add a page`로 추가
- 페이지 hover시 +로 sub-page 추가
- 페이지 hover시 옵션 버튼으로 페이지 삭제, rename, duplicate, ~copy link~
- 페이지 드래그로 위치 변경

## block

엔터시 text 타입으로 자동 생성됨

### block에 hover
- add 버튼: 클릭시 현재 블록 하단에 새 블록 추가
  - ![image](https://user-images.githubusercontent.com/44664867/148735264-7e9f2ff0-473b-4ecb-9f2f-843cd74ad1d9.png)

- 옵션(?) 버튼: **드래그**시 블록 위치 이동, **클릭**시 메뉴 오픈
  - ![image](https://user-images.githubusercontent.com/44664867/148735310-f74f0dee-611a-4fec-8f56-bd781a44f58b.png)  
  - ![image](https://user-images.githubusercontent.com/44664867/148736042-79b961a5-0e4c-4f7d-8198-ba9570b08d4c.png)
  - 메뉴: 삭제, 복사(하단에 블록 복사), color(highlight), turn into -> 해당 블록 전체를 감싼 tag 변경하는 느낌
  - 마지막 수정 날짜 및 작성자 표기

### block 내의 text drag
![image](https://user-images.githubusercontent.com/44664867/148735408-bb703cea-1015-48d2-b4e9-72d1ea14748e.png)
- 순서대로 [~turn into, link, comment,~ text formatting, text color(highlight), ~mention,~ option(위의 block option)]

### block에서 구현하고싶은 기능
- comment, turn into page, move to(page), menotion, link 기능 제외한 나머지 기능
- formatting: 굵게, 기울임, 아래선, 취소선, 코드

## /

- block의 타입을 정함
- Text(기본), Page(sub-page), Todo, Heading1~3, bulleted list(ul), number list(ol), toggle list, quote, code block(2순위)

**Comment by GeonHyeongKim** [comment]
## page
* 페이지 hover시 옵션 버튼으로 [즐겨찾기, copy link]는 빼는건가요?

## block에 hover
* add 버튼: 클릭시 현재 블록 하단에 새 블록 추가 -> 다른 선택 없이 바로 block 추가하기! 동의합니다.

## block에서 구현하고싶은 기능 중
댓글(comment)까지는 되야하지 않을까요?

## block 타입은 같이 의논해서 정해야 할 듯해요
타입이 정해지면, turn into도 가능해지질 것 같습니다!

**Comment by chahtk** [comment]
@GeonHyeongKim page의 즐겨찾기와 block의 comment는 빼는 편이 좋다는 생각이고(그다지 눈에 띄지 않는 작업인데 반해 fe, be 양 쪽에 일이 생겨서...), link는 다시 생각해보겠습니다..

**Comment by chahtk** [comment]
- ~tab을 이용한 depth 변경(다른 블록에 종속 or 해제)~ -> 2순위
- ~블록 횡으로 쌓기(드래그로 놓을 수 있음)~ -> 3순위

**Comment by chahtk** [comment]
color 및 트랜잭션 형식, 커서위치 변경시 소켓? http?

**Comment by chahtk** [comment]
### 블록 옵션
- 삭제
- 복사(하단에 블록 복사)
- color(highlight)
- turn into (block type) : page 포함(sub page 생성)

### 텍스트 드래그
- turn into
- text formatting
- text color (background, heighlight)
- option(block option -> 중복 기능이기 때문에 굳이 보여줘야하나? 2순위)

### 슬래쉬(블록타입 생성)
- Text(기본)
- Page(sub-page)
- Todo, Heading1~3
- bulleted list(ul)
- number list(ol)
- toggle list
- quote
- code block(2순위)

### tab으로 depth 변경하여 블록 종속 관계 변화 (2순위)

### 블록 횡 쌓기 (3순위)

### 트랜잭션 형식?

**Comment by chahtk** [comment]
socket : 커서 + 문서 업데이트 noti (with version)
http: saveTransaction , syncRecordValues

**Comment by chahtk** [comment]
update(혹은 생성된) 블록은 변경사항 뿐 아니라 전부 transaction에 포함하여 보낸다

**Comment by chahtk** [comment]
### 블록 구조 분석

1 data-block (notion.selectable, notion.text-block(blocktype) , margin, width, height 등 "껍질" 처리
    2? : styling (color) , flex(list일 때, 말머리 + 컨텐츠를 보여주기 위해) : padding, color 등 "내부" 처리 -> 횡블록시 하위 블록을 위한 FLEX

     [ list, todo, 
     2.xxx -> 블록 타입에 따라 2-3 사이에 추가 depth로 들어감(뒤의 것들의 상위)
     2.xxx : 말머리, 
     2.xxx+1 : 말머리 컨텐츠

         3(flex) : 밑의 no translate와 세트, quote 일 때 border-left가 들어감
            4 : content box(no translate) --> 내용, 줄바꿈해도 이 박스 안에서 (기타 특성 모두 여기)
