### ISSUE TITLE
CORS 이슈

### ISSUE THREAD

**Issue by chahtk** [njsh4261/SGS_Last_Punch#76]
![image](https://user-images.githubusercontent.com/44664867/149607763-a6f3e38d-e9b3-4bd3-b16f-9c5e44ef5058.png)
- cors 문제 발생
- loclashot:3000 번에 대해 (혹은 개발용으로 모든 주소에 대해) 접근을 허용해야할 듯 (`Access-Control-Allo-Origin`)

**Comment by SooKim1110** [comment]
feat/auth/authentication 브랜치에 CORS 설정을 추가하여 push 했습니다.
회원가입과 로그인이 잘 동작하는 것을 확인했습니다.
도커 실행하실 때 pull 이랑 build 한번씩만 다시 해주세요. 

현재 gateway에만 CORS 설정을 적용해서( auth-server에도 적용하니 Access-Control-Allow-Origin 헤더를 두 개 보내게 되어서 에러가 나더라구요. 헤더 중복 제거를 하는 방법도 있는 것 같긴 합니다. (참고: https://yangbongsoo.tistory.com/18))
X-AUTH-TOKEN 헤더를 보낼 때 제대로 auth-server까지 토큰 헤더가 도달하지 못하는 문제가 생길 수도 있을 것 같습니다. 혹시 /auth/reissue, /auth/verify API를 사용하시다가 이런 문제가 발생한다면 알려주세요!

**Comment by chahtk** [comment]
수고하셨습니다 지수님. 해당 부분 내일이나 월요일에 확인해보겠습니다!!!

**Comment by yangbongsoo** [comment]
@SooKim1110 님 안녕하세요. 블로그 유입경로 보다가 `https://github.com/njsh4261/SGS_Last_Punch` 도메인이 떠서 신기해서 구경하게 됐습니다. ㅎㅎㅎ CORS 이슈 해결을 위해 gateway에 관련 설정을 적용하는 것보다 auth server 컨트롤러에서 `@CrossOrigin(origins = "http://localhost:3000", allowedHeaders = "*")` 설정을 추가하는것은 어떨까요? gateway 에서는 관련 헤더들을 모두 bypass 시키구요. 블로그 내용도 gateway 에서는 bypass 시키고 뒷단 서버에서 처리 하자는 얘기였습니다.

그리고 AccessTokenFilter 는 아래처럼 바꾸는게 좀 더 좋지 않을까 해서 의견 드립니다. ㅎㅎ
```java
import org.springframework.util.ObjectUtils;

// equest.getHeaders().get("X-AUTH-TOKEN").get(0) 대신 getFirst
String accessToken = request.getHeaders().getFirst("X-AUTH-TOKEN");

// empty string 만 확인하지 말고 null 과 empty string 둘다 확인
if (ObjectUtils.isEmpty(accessToken)) throw new NullPointerException();
```

**Comment by SooKim1110** [comment]
@yangbongsoo 
헉 안녕하세요! 
먼저, 좋은 글 써주셔서 감사드립니다! 글 읽고 많이 배웠습니다. 많이 부족한 코드인데 코드도 읽어주셔서 감사합니다. AccessTokenFilter 부분은 고쳐주신 것처럼 수정하는 것이 훨씬 깔끔해보입니다! 감사합니다. 

사실 블로그 글을 읽으면서 다음 부분이 조금 이해가 안 갔어서 질문드리고 싶은 점이 있습니다.

> 문제는 Spring Cloud Gateway 에서 준 preflight 응답에서 Access-Control-Allow-Origin 값이 있어야 하는데 정할 수가 없다. 뒷단 서버들의 도메인들이 다 다르기 때문이다. 설령 뒷단 서버 도메인들을 다 추가한다 하더라도 동적으로 새롭게 늘어갈 때마다 추가해줘야 한다. 그리고 allow origin 검사가 exact matching 이기 때문에 *.ybs.com 같이 패턴을 넣는것도 불가능하다.

저희 서비스같은 경우는 Access-Control-Allow-Origin에 웹 프론트 주소 “http://localhost:3000” 이 들어갈 것 같은데 모든 백엔드 서비스에서 허용해야하는 Origin 이 같고, 같은 cors 정책을 사용하는 경우에는 혹시 gateway에서 cors 설정을 해주는 방식이 뒷단 서버들에서 처리하는 방식보다 나을까요? 혹시 제가 잘못 이해한 것인지 궁금합니다.

**Comment by yangbongsoo** [comment]
@SooKim1110 님. 여기는 다른분들도 참여하시는 공간이라 답변은 [여기](https://github.com/yangbongsoo/tistory-comments/issues/3) 에 남겼습니다.
