### ISSUE TITLE
Note 개발 일정(1~3)

### ISSUE THREAD

**Issue by GeonHyeongKim** [njsh4261/SGS_Last_Punch#85]
## 프로토 타입 1 → 1주차(01.17 ~ 01.21)

1. block 에 text만 적기(FE)
2. block 에 상대방 실시간 공동 편집(BE)
3. 같은 block 에서 편집하지 않음

## 프로토 타입 2 → 2~4주차(01.24 ~ 02.11)

1. 공동편집(FE) + FE-BE 연결
2. 커서 위치
3. blcok 선점

## 프로토 타입 3 → 2~4주차(01.24 ~ 02.11)

1. block type 적용 → 페이지화, 포메팅...등
2. Turn into (Block type 바꾸기) → /
3. 블록 옵션 (제외. turn into)

**Comment by chahtk** [comment]
### 데이터 형식(1차)
- noteId, blockId, blockType: text, content
